#ifndef CFILE_TYPE_H
#define CFILE_TYPE_H

enum CFileType {
  // Sub Types

  CFILE_TYPE_NONE  = 0,
  CFILE_TYPE_INODE = (1<<16),
  CFILE_TYPE_TEXT  = (1<<17),
  CFILE_TYPE_BIN   = (1<<18),
  CFILE_TYPE_IMAGE = (1<<19),
  CFILE_TYPE_EXEC  = (1<<20),
  CFILE_TYPE_SOUND = (1<<21),

  //--------

  // Combination Sub Types

  CFILE_TYPE_BIN_IMAGE       = (CFILE_TYPE_TEXT | CFILE_TYPE_IMAGE),
  CFILE_TYPE_TEXT_IMAGE      = (CFILE_TYPE_TEXT | CFILE_TYPE_IMAGE),
  CFILE_TYPE_TEXT_IMAGE_EXEC = (CFILE_TYPE_TEXT | CFILE_TYPE_IMAGE),
  CFILE_TYPE_TEXT_EXEC       = (CFILE_TYPE_TEXT | CFILE_TYPE_EXEC),
  CFILE_TYPE_BIN_EXEC        = (CFILE_TYPE_BIN  | CFILE_TYPE_EXEC),
  CFILE_TYPE_BIN_SOUND       = (CFILE_TYPE_BIN  | CFILE_TYPE_SOUND),

  //--------

  // File Types

  CFILE_TYPE_INODE_FIFO  = (CFILE_TYPE_INODE + 1),
  CFILE_TYPE_INODE_CHR   = (CFILE_TYPE_INODE + 2),
  CFILE_TYPE_INODE_DIR   = (CFILE_TYPE_INODE + 3),
  CFILE_TYPE_INODE_BLK   = (CFILE_TYPE_INODE + 4),
  CFILE_TYPE_INODE_REG   = (CFILE_TYPE_INODE + 5),
  CFILE_TYPE_INODE_LNK   = (CFILE_TYPE_INODE + 6),
  CFILE_TYPE_INODE_SOCK  = (CFILE_TYPE_INODE + 7),

  CFILE_TYPE_TEXT_PLAIN  = (CFILE_TYPE_TEXT  + 20),
  CFILE_TYPE_TEXT_BINARY = (CFILE_TYPE_BIN   + 21),
  CFILE_TYPE_TEXT_HTML   = (CFILE_TYPE_TEXT  + 22),
  CFILE_TYPE_TEXT_XML    = (CFILE_TYPE_TEXT  + 24),
  CFILE_TYPE_TEXT_TAR    = (CFILE_TYPE_BIN   + 25),
  CFILE_TYPE_TEXT_TGZ    = (CFILE_TYPE_BIN   + 26),
  CFILE_TYPE_TEXT_GZIP   = (CFILE_TYPE_BIN   + 27),

  CFILE_TYPE_IMAGE_BMP   = (CFILE_TYPE_BIN_IMAGE       + 40),
  CFILE_TYPE_IMAGE_EPS   = (CFILE_TYPE_TEXT_IMAGE_EXEC + 41),
  CFILE_TYPE_IMAGE_GIF   = (CFILE_TYPE_BIN_IMAGE       + 42),
  CFILE_TYPE_IMAGE_ICO   = (CFILE_TYPE_BIN_IMAGE       + 43),
  CFILE_TYPE_IMAGE_IFF   = (CFILE_TYPE_BIN_IMAGE       + 44),
  CFILE_TYPE_IMAGE_JPG   = (CFILE_TYPE_BIN_IMAGE       + 45),
  CFILE_TYPE_IMAGE_PCX   = (CFILE_TYPE_BIN_IMAGE       + 46),
  CFILE_TYPE_IMAGE_PNG   = (CFILE_TYPE_BIN_IMAGE       + 47),
  CFILE_TYPE_IMAGE_PPM   = (CFILE_TYPE_BIN_IMAGE       + 48),
  CFILE_TYPE_IMAGE_PS    = (CFILE_TYPE_TEXT_IMAGE_EXEC + 49),
  CFILE_TYPE_IMAGE_PSP   = (CFILE_TYPE_BIN_IMAGE       + 50),
  CFILE_TYPE_IMAGE_SGI   = (CFILE_TYPE_BIN_IMAGE       + 51),
  CFILE_TYPE_IMAGE_SVG   = (CFILE_TYPE_TEXT_IMAGE_EXEC + 52),
  CFILE_TYPE_IMAGE_TGA   = (CFILE_TYPE_BIN_IMAGE       + 53),
  CFILE_TYPE_IMAGE_TIF   = (CFILE_TYPE_BIN_IMAGE       + 54),
  CFILE_TYPE_IMAGE_XBM   = (CFILE_TYPE_TEXT_IMAGE      + 55),
  CFILE_TYPE_IMAGE_XPM   = (CFILE_TYPE_TEXT_IMAGE      + 56),
  CFILE_TYPE_IMAGE_XWD   = (CFILE_TYPE_BIN_IMAGE       + 57),

  CFILE_TYPE_APP_EXEC    = (CFILE_TYPE_BIN_EXEC  + 60),
  CFILE_TYPE_APP_CORE    = (CFILE_TYPE_BIN_EXEC  + 61),
  CFILE_TYPE_APP_SH      = (CFILE_TYPE_TEXT_EXEC + 62),
  CFILE_TYPE_APP_CSH     = (CFILE_TYPE_TEXT_EXEC + 63),
  CFILE_TYPE_APP_KSH     = (CFILE_TYPE_TEXT_EXEC + 64),
  CFILE_TYPE_APP_PERL    = (CFILE_TYPE_TEXT_EXEC + 65),
  CFILE_TYPE_APP_PYTHON  = (CFILE_TYPE_TEXT_EXEC + 66),
  CFILE_TYPE_APP_TCL     = (CFILE_TYPE_TEXT_EXEC + 67),
  CFILE_TYPE_APP_PHP     = (CFILE_TYPE_TEXT_EXEC + 68),
  CFILE_TYPE_APP_JAVA    = (CFILE_TYPE_TEXT_EXEC + 69),

  CFILE_TYPE_SOUND_WAV = (CFILE_TYPE_BIN_SOUND + 80),

  //--------

  // Aliases

  CFILE_TYPE_APP_EPS     = CFILE_TYPE_IMAGE_EPS,
  CFILE_TYPE_APP_PS      = CFILE_TYPE_IMAGE_PS,
  CFILE_TYPE_APP_SVG     = CFILE_TYPE_IMAGE_SVG,

  CFILE_TYPE_TEXT_SH     = CFILE_TYPE_APP_SH,
  CFILE_TYPE_TEXT_CSH    = CFILE_TYPE_APP_CSH,
  CFILE_TYPE_TEXT_KSH    = CFILE_TYPE_APP_KSH,
  CFILE_TYPE_TEXT_PERL   = CFILE_TYPE_APP_PERL,
  CFILE_TYPE_TEXT_PYTHON = CFILE_TYPE_APP_PYTHON,
  CFILE_TYPE_TEXT_TCL    = CFILE_TYPE_APP_TCL,
  CFILE_TYPE_TEXT_PHP    = CFILE_TYPE_APP_PHP,
  CFILE_TYPE_TEXT_JAVA   = CFILE_TYPE_APP_JAVA
};

#endif
